# Generated by Django 3.0.6 on 2020-05-27 19:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('license_plate', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='License ID')),
                ('doors', models.IntegerField(max_length=10, verbose_name='Doors')),
                ('diesel', models.BooleanField()),
                ('status', models.IntegerField(choices=[(1, 'Available'), (2, 'Leased'), (3, 'Booked')], default=1, verbose_name='Status')),
                ('size', models.CharField(max_length=10, verbose_name='Car Size')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('since', models.TimeField()),
                ('until', models.TextField()),
                ('history_comments', models.TextField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renting.Car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renting.Client')),
            ],
            options={
                'unique_together': {('client', 'car')},
            },
        ),
        migrations.AddField(
            model_name='car',
            name='services',
            field=models.ManyToManyField(through='renting.Rent', to='renting.Client'),
        ),
    ]
